const options = {
    ignoreHref: true,
    ignoreImage: true,
    noLinkBrackets: true,
    preserveNewlines: false,
    noLinkBrackets: true,
    ignoreHref: true,
    wordwrap: 1,
    ignoreImage: true,
    encodeCharacters: {
        "\n": " ",
        "\n\n": " ",
        "\n\n\n": " ",
        "\n\n\n\n": " ",
        "\n\n\n\n\n": " ",
        "\n\n\n\n\n\n": " ",
        "\n\n\n\n\n\n\n": " ",
        "\n\n\n\n\n\n\n\n": " ",
        "/": " ",
        "\\": " ",
        "(": " ",
        ")": " ",
        "[": " ",
        "]": " ",
        "\r": " ",
        "\t": " ",
        "\f": " ",
        "\v": " ",
        "\u00A0": " ",
        "*": " ",
    },
    whitespaceCharacters: "\t\r\n",
    selectors: [
        { selector: "a", format: "skip" },
        { selector: "img", format: "skip" },
        { selector: "script", format: "skip" },
        { selector: "style", format: "skip" },
        { selector: "br", options: { itemPrefix: " " } },
        { selector: "header", format: "skip" },
        { selector: "footer", format: "skip" },
        { selector: "ul", options: { itemPrefix: " " } },
        { selector: "ol", options: { itemPrefix: " " } },
        // { selector: 'li', options: { itemPrefix: " " }},
        { selector: "p", options: { itemPrefix: " " } },
        { selector: "h1", options: { itemPrefix: " " } },
        { selector: "h2", options: { itemPrefix: " " } },
        { selector: "h3", options: { itemPrefix: " " } },
        { selector: "h4", options: { itemPrefix: " " } },
        { selector: "h5", options: { itemPrefix: " " } },
        { selector: "h6", options: { itemPrefix: " " } },
        { selector: "table", options: { itemPrefix: " " } },
        // { selector: 'tr', options: { itemPrefix: "" }},
        //{ selector: 'td', options: { itemPrefix: "" }},
        //{ selector: 'th', options: { itemPrefix: "" }},
        //{ selector: 'title', options: { itemPrefix: "" }},
    ],
    decodeEntities: true,
};
